services:
  php:
    build: .
    ports:
      - "8091:80"
    depends_on:
      - database
      - gotenberg
      - mailer
    restart: always
    environment:
      DATABASE_URL: "postgresql://app:app@database:5432/app?serverVersion=16&charset=utf8&driver=pdo_pgsql"
      MAILER_DSN: "smtp://mailer:1025"
      GOTENBERG_DSN: "http://gotenberg:3000"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  gotenberg:
    image: gotenberg/gotenberg:8

  mailer:
    image: axllent/mailpit
    ports:
      - "8026:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database_data: